GET http://localhost:5000/account/

###

GET http://localhost:5000/account/5f3034984d53ab4c02d2346a

###

POST http://localhost:5000/account/register
Content-Type: application/json

{
    "name": "Rahul",
    "email": "rahul@gmail.com",
    "password": "12345"
}

###

POST http://localhost:5000/account/login
Content-Type: application/json

{
    "email":"surbhi@GMAIl.com",
    "password":"1234"

}

###

DELETE http://localhost:5000/account/5f3180410e55e014b39dbdc7
###

POST http://localhost:5000/account/update/5f3034984d53ab4c02d2346a
Content-Type: application/json

{
    "name":"Surbhi",
    "email": "surbhi@gmail.com",
    "password": "1234"
}