GET http://localhost:5000/account/

###

POST http://localhost:5000/account/register
Content-Type: application/json

{
    "name": "Surbhi",
    "email": "surbhi@gmail.com",
    "password": "1234"
}

###

POST http://localhost:5000/account/login
Content-Type: application/json

{
    "email":"surbhi@GMAIL.com",
    "password":"1234"

}